jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set Build Number
      run: 'echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Setup Gradle
      uses: GeyserMC/actions/setup-gradle-composite@master
      with:
        checkout_ref: ${{ inputs.ref }}
        checkout_repository: ${{ inputs.repository }}
        setup-gradle_cache-read-only: true
        setup-java_java-version: 21
    - continue-on-error: true
      name: Build Geyser
      run: ./gradlew build
    - continue-on-error: true
      if: success()
      name: Archive Artifacts
      uses: GeyserMC/actions/upload-multi-artifact@master
      with:
        artifacts: 'bootstrap/mod/fabric/build/libs/Geyser-Fabric.jar

          bootstrap/mod/neoforge/build/libs/Geyser-NeoForge.jar

          bootstrap/standalone/build/libs/Geyser-Standalone.jar

          bootstrap/spigot/build/libs/Geyser-Spigot.jar

          bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar

          bootstrap/velocity/build/libs/Geyser-Velocity.jar

          bootstrap/viaproxy/build/libs/Geyser-ViaProxy.jar'
name: Build Remote
on:
  repository_dispatch:
    types: trigger-ga___build-remote.yml
permissions: {}
