jobs:
  dispatch-preview:
    secrets: inherit
    uses: GeyserMC/actions/.github/workflows/upload-preview.yml@master
    with:
      build: ${{ inputs.build }}
      files: 'bungeecord:Geyser-BungeeCord.jar

        fabric:Geyser-Fabric.jar

        neoforge:Geyser-NeoForge.jar

        spigot:Geyser-Spigot.jar

        standalone:Geyser-Standalone.jar

        velocity:Geyser-Velocity.jar

        viaproxy:Geyser-ViaProxy.jar

        '
      project: geyserpreview
      runId: ${{ inputs.runId }}
      version: ${{ inputs.version }}
name: Dispatch Preview
on:
  repository_dispatch:
    types: trigger-ga___dispatch-preview.yml
