jobs:
  build:
    permissions: {}
    secrets: {}
    uses: GeyserMC/Geyser/.github/workflows/build-remote.yml@master
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}
  preview:
    if: 'contains(github.event.pull_request.labels.*.name, ''PR: Needs Testing'')'
    needs:
    - build
    secrets: inherit
    uses: GeyserMC/actions/.github/workflows/upload-preview.yml@master
    with:
      build: ${{ github.run_number }}
      files: 'bungeecord:Geyser-BungeeCord.jar

        fabric:Geyser-Fabric.jar

        neoforge:Geyser-NeoForge.jar

        spigot:Geyser-Spigot.jar

        standalone:Geyser-Standalone.jar

        velocity:Geyser-Velocity.jar

        viaproxy:Geyser-ViaProxy.jar

        '
      project: geyserpreview
      runId: ${{ github.run_id }}
      version: pr.${{ github.event.pull_request.number }}
name: Process Pull Request
on:
  repository_dispatch:
    types: trigger-ga___pull-request.yml
